### ISSUE TITLE
When all dependencies are removed, it doesn't clear `deps`

### ISSUE THREAD

**Issue by bfreis** [tcncloud/wollemi#21]
I encountered an issue where when a package has all its dependencies removed, wollemi won't touch the `deps` attribute and it will leave all deps there.

I think it's caused by this check:

https://github.com/tcncloud/wollemi/blob/3c60e35b7b00d2b32fa01810baba1b825eb75071/domain/wollemi/service_format.go#L644-L646

Since the result is no deps, the check fails, and it doesn't clear the `deps`.

**Comment by brian-bice** [comment]
Thanks @bfreis. This issue should be fixed now on master.
