### ISSUE TITLE
👋🏻  VSCode Extension

### ISSUE THREAD

**Issue by jamesjarvis** [tcncloud/wollemi#23]
Hi there! 👋🏻 amazing tool btw!
As I tend to use vscode (and was a bit jealous of that vim integration!) I've created a little vscode extension that runs Wollemi on file save.
Project link: https://github.com/jamesjarvis/vs-wollemi
VSCode marketplace link: https://marketplace.visualstudio.com/items?itemName=jamesjarvis.vs-wollemi

I was wondering if I could get your opinions on it? Thanks!

**Comment by namtzigla** [comment]
Hi James, 

Nice job, I just test your plugin and looks promising. So far we've been using wk-j.save-and-run plugin to integrate that but we would love to have a specialized plugin.

**Comment by brian-bice** [comment]
Nice! I have not used vscode so it took me awhile to figure out that `vs-wollemi.shell` needed to be set for the extension to work for me. Now that I have that set the extension seems to work just like I would expect. Thanks @jamesjarvis!

**Comment by jamesjarvis** [comment]
@brian-bice thanks for the feedback! I left the option in as it worked locally (on my MacBook) without needing config, however on other systems it seems to require a shell to be specified.
I think I'll update the docs to highlight that this setting may require setting 😁
