### ISSUE TITLE
Correct format of .wollemi.json

### ISSUE THREAD

**Issue by sagikazarmark** [tcncloud/wollemi#3]
What is the correct format of the .wollemi.json? The examples in the README are not valid JSONs and it's not clear how the config file should look like.

**Comment by brian-bice** [comment]
@sagikazarmark  I updated the README with more detail about configuration and fixed the examples with invalid json. Let me know if that helps clear up the confusion around configuration.

**Comment by sagikazarmark** [comment]
Perfect! Thanks a lot!
