### ISSUE TITLE
plz fmt

### ISSUE THREAD

**Issue by sagikazarmark** [tcncloud/wollemi#6]
Please added an `fmt` command in 15.6.0: https://github.com/thought-machine/please/releases/tag/v15.6.0

It uses a modified version of the buildifier tool library.

**Comment by brian-bice** [comment]
Hi @sagikazarmark. Sorry I have been very busy on other work. That's great to hear about the new plz command. I would assume the builtin command does not do rule generation or dependency management does it? Was there a change we should make here or were you proposing something else?

**Comment by sagikazarmark** [comment]
Sorry for the late reply. No, it doesn't do rule generation.

I was wondering if it would make sense to offload formatting to the new command and keep the focus on rule generation in wollemi.

**Comment by sagikazarmark** [comment]
@brian-bice actually: would you accept a PR that replaces the buildtools module with https://github.com/peterebden/buildtools ?

Looks like adding f-string support is trivial?

**Comment by namtzigla** [comment]
@sagikazarmark sure, we would like that

**Comment by brian-bice** [comment]
Definitely.

**Comment by sagikazarmark** [comment]
I'm not sure how you want to proceed with this issue. I've sent a PR for replacing the build tools package. As I mentioned, Please implemented an fmt command for formatting BUILD files, so that feature could be removed from wollemi.

Feel free to close this issue.
